version: "2"

run:
  timeout: 3m
  build-tags:
    - integration

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gocritic

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - commentedOutCode
    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam

formatters:
  enable:
    - gofmt
    - goimports
